version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616" # broker (admin:adminactivemq)(amq:amq)
      - "8161:8161"   # web    http://boot2docker:8161/admin (admin:admin)

  test-webapp:
    depends_on:
      - db
      - activemq
    image: my-app
    container_name: my-container
    ports:
      - "8080:8080"
    environment:
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
